name: retrieve aio commits
on:
  workflow_dispatch:
  schedule:
    - cron: '15 2 * * *'
jobs:
  commits:
    runs-on: ubuntu-latest
    steps:
      - name: get commits
        uses: geromegrignon/ng-aio-gen@v1.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}