name: retrieve aio commits
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      - name: close the pull request
        uses: geromegrignon/ng-aio-gen@v1.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}