on: workflow_dispatch
jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      - name: close the pull request
        uses: geromegrignon/ng-aio-gen@v1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}